### ISSUE TITLE
node-uuid is deprecated

### ISSUE THREAD

**Issue by piorek** [restify/node-restify#1283] opened 2017-03-01 13:06 UTC
While doing npm install im getting deprecation message

> npm WARN deprecated node-uuid@1.4.7: use uuid module instead

**Comment by fmauNeko** [comment] 2017-03-15 11:00
Duplicate of #1233, already fixed in the 5.x branch.

**Comment by piorek** [comment] 2017-03-16 13:45
So you are not planning to do it in 4.x?

**Comment by retrohacker** [comment] 2017-06-27 19:42
This has been backported to both the 4.x and 5.x branches. Marking this as resolved for now :heart:

**Closed** 2017-06-27 19:42 UTC
Labels: Dependencies, fixed but not yet released

**Comment by piorek** [comment] 2017-06-28 07:05
@retrohacker Thanks!
