### ISSUE TITLE
CORS doesn't work with headers

### ISSUE THREAD

**Issue by DarkPark** [restify/node-restify#781] opened 2015-03-24 14:19 UTC
CORS module is enabled.

```
/**
 * @api {get} /sessions Receive a list of a user sessions.
 *
 * @apiVersion 1.0.0
 * @apiName getSessions
 * @apiGroup Sessions
 */
```

Test request on the documentation page is okay.

Just add header option:

```
/**
 * @api {get} /sessions Receive a list of a user sessions.
 *
 * @apiVersion 1.0.0
 * @apiName getSessions
 * @apiGroup Sessions
 *
 * @apiHeader {string} Authorization Bearer token for the user session.
 */
```

This doesn't work at all. Fails on OPTION request.

Request headers:

```
OPTIONS /sessions?{} HTTP/1.1
Host: localhost:9090
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Access-Control-Request-Method: GET
Origin: http://localhost:63342
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36
Access-Control-Request-Headers: accept, authorization, content-type
Accept: */*
Referer: http://localhost:63342/FortNotes/doc/api/index.html
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,ru;q=0.6
```

Response headers:

```
HTTP/1.1 405 Method Not Allowed
Allow: GET
Content-Type: application/json
Content-Length: 67
Date: Tue, 24 Mar 2015 14:01:36 GMT
Connection: keep-alive
```

It's also not clear why there are some chars in the end of the path line.
The description is:

```
@api {get} /sessions
```

But the request is:

```
OPTIONS /sessions?{}
```

**Comment by micahr** [comment] 2015-09-08 02:24
Could you provide an example of the code you are running? The code comments aren't quite enough to discern what is going on.

**Comment by acroyear** [comment] 2016-02-14 20:45
This is happening to me as well. The problem is that my app itself, my own code, is not sending the OPTIONS request. Chrome has, sometime in the last 2 or 3 releases, decided to automatically send the preflight for any and all CORS requests, and it does acknowledge all security settings that return (e.g., the methods allowed, the headers allowed, etc - the CORS simple case will need to support allowed-methods in the same way as it supports allowed-headers). It is out of the hands of the developer of the app or webpage, and it can't be turned off. I will guess Firefox will join it in the next few releases if it doesn't already.

I followed a hack from another discussion on this subject to basically implement my own options handler to work around it.

**Comment by retrohacker** [comment] 2017-04-29 14:19
Closing this as a duplicate of #664, of which there is an open PR addressing.

If I am missing a nuance here, please correct me and we can re-open to discuss :heart:

**Closed by retrohacker** 2017-04-29 14:19 UTC
