### ISSUE TITLE
Node.js 6.1 DeprecationWarning: process.EventEmitter is deprecated

### ISSUE THREAD

**Issue by nodesocket** [restify/node-restify#1077] opened 2016-05-07 20:12 UTC
When running restify on Node.js 6.1 seeing:

````
(node:10003) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
````

I did a quick grep through the `lib/` directory, but couldn't find where `process.EventEmitter` is being used.

**Comment by chadmurphy** [comment] 2016-05-10 21:28
The issue is in spdy.

**Comment by martip-sainsburys** [comment] 2016-05-11 10:19
+1

**Comment by NKITMedia** [comment] 2016-05-11 10:34
same here

**Comment by DonutEspresso** [comment] 2016-05-11 18:07
Dupe of #1067

**Closed by DonutEspresso** 2016-05-11 18:07 UTC

**Comment by israel-viveros** [comment] 2016-05-24 17:44
same problem
