### ISSUE TITLE
Custom formatter not supported

### ISSUE THREAD

**Issue by anup4f82** [restify/node-restify#1311] opened 2017-04-19 04:24 UTC
Our Client sends the Accept Header as 'application/json; v=1'. I added the below custom formatter - 
 
```
formatters: {
    'application/json;v=1': function format(req, res, body, cb) {
      if (body instanceof Error)
        return body.stack;
      if (Buffer.isBuffer(body))
        return cb(null, body.toString('base64'));
      return cb(null, util.inspect(body));
    }
  }
```

But when I make a Request, it throws the below error - 

 ```
  { code: 'NotAcceptableError',
     message: 'Server accepts: application/json,application/json,text/plain,application/octet-stream,application/javascript' } 
```

If you see the error - it has 2 application/json entries. So it looks like it's not taking the v=1.

I also tried adding the formatter as 'application/json;v=1,q=0.9', but that didn't work either.

**Comment by retrohacker** [comment] 2017-04-26 21:12
Hey @anup4f82, is this a duplicate of https://github.com/restify/node-restify/issues/1219 ?

**Comment by retrohacker** [comment] 2017-06-27 17:33
Closing this as a duplicate of #1219. If I'm missing a nuance here, please comment and we can re-open to discuss :heart:

**Closed by retrohacker** 2017-06-27 17:33 UTC
Labels: Waiting on Response
