### ISSUE TITLE
JSON types such as "application/hal+json" do not work

### ISSUE THREAD

**Issue by Marclev78** [restify/node-restify#1442] opened 2017-08-08 17:32 UTC
# Bug Report
Restify cannot handle JSON content-types other than `application/json`

## Restify Version
5.0.1

## Node.js Version
8.0.0

## Expected behaviour

When submitting a valid JSON document using a content type such as "application/hal+json", it should be recognized as a JSON dialect and the request body be turned into a JSON object.

## Actual behaviour

Restify is unable to interpret the content type and returns the request body as an instance of `Buffer`.

> This section details what restify actually did when you ran your code

Restify fails to parse the request as being JSON.

## Repro case

An example request could look like:

```
    request({
      url: url,
      method: "post",
      json: true,
      headers: {
        "content-type": "application/hal+json"
      },
      body: {a: "b"}
    }, function (err, response, responseData) {
      if (err) {
        //...
      } else {
        //...
      }
    })
```
## Cause

As neither `bodyParser` nor `jsonBodyParser` know about content types other than `application/json`, the request is not handled as valid JSON.

## Are you willing and able to fix this?

Yes

**Comment by mattbishop** [comment] 2017-08-08 19:04
Siren uses a different media type too: `application/vnd.siren+json`

https://github.com/kevinswiber/siren

**Comment by mattbishop** [comment] 2017-08-08 19:06
Collection JSON has it's own: `application/vnd.collection+json`

http://amundsen.com/media-types/collection/format/

**Comment by mattbishop** [comment] 2017-08-19 16:28
It looks like the way to configure restify to take different Media Types as JSON is to override the formatter. Seems a bit brute-force but here is an example: https://github.com/Juravenator/restify-json-hal/blob/master/index.js#L13

**Comment by retrohacker** [comment] 2017-08-23 15:57
Hey @mattbishop and @Marclev78,

Thank you for taking the time to open this bug report, for using our template, and for taking the time to follow up and help the community :heart:

I apologize for my ignorance here, but I'm not sure I've ever seen this format for a `Content-Type` of the format `[discrete-type]/something.something+[composite-type]` before. Is this in an RFC somewhere? I'm looking through https://www.ietf.org/rfc/rfc2045.txt and I'm not seeing it, though I may be looking in the wrong place.

**Comment by retrohacker** [comment] 2017-08-23 15:59
Marking this as unconfirmed until we can dig up a specification documenting this behaviour, once we do we can remove that label and work together on a PR :smile:

**Comment by mattbishop** [comment] 2017-08-25 20:55
I have multiple REST specs for your consideration:

Name | Definition URL | Media Type | IANA
---- | ---- | ---- | ----
Siren Hypermedia | https://github.com/kevinswiber/siren | `application/vnd.siren+json` | https://www.iana.org/assignments/media-types/application/vnd.siren+json
Collection JSON | http://amundsen.com/media-types/collection/format/ |  `application/vnd.collection+json` | https://www.iana.org/assignments/media-types/application/vnd.collection+json
HAL | http://stateless.co/hal_specification.html | `application/vnd.hal+json` | https://www.iana.org/assignments/media-types/application/vnd.hal+json
JSON API | http://jsonapi.org | `application/vnd.api+json` | http://www.iana.org/assignments/media-types/application/vnd.api+json


There are more; go to this page https://www.iana.org/assignments/media-types/media-types.xhtml and search for `+json` to see the variety.

**Comment by mattbishop** [comment] 2017-09-01 14:17
I have another example of a format that uses this pattern of media type: Transit: https://github.com/cognitect/transit-format

Their type is `application/transit+json`

**Comment by DonutEspresso** [comment] 2017-09-03 05:10
Thanks for the extensive documentation, @mattbishop! Looks like this is covered in [RFC6838](https://tools.ietf.org/html/rfc6838#section-4.2.8). I'll copy the text here:

```
4.2.8.  Structured Syntax Name Suffixes

   XML in MIME [RFC3023] defined the first such augmentation to the
   media type definition to additionally specify the underlying
   structure of that media type.  To quote:

      This document also standardizes a convention (using the suffix
      '+xml') for naming media types ... when those media types
      represent XML MIME (Multipurpose Internet Mail Extensions)
      entities.

   That is, it specified a suffix (in that case, "+xml") to be appended
   to the base subtype name.

   Since this was published, the de facto practice has arisen for using
   this suffix convention for other well-known structuring syntaxes.  In
   particular, media types have been registered with suffixes such as
   "+der", "+fastinfoset", and "+json".  This specification formalizes
   this practice and sets up a registry for structured type name
   suffixes.

   The primary guideline for whether a structured type name suffix is
   registrable is that it be described by a readily available
   description, preferably within a document published by an established
   standards-related organization, and for which there's a reference
   that can be used in a Normative References section of an RFC.

   Media types that make use of a named structured syntax SHOULD use the
   appropriate registered "+suffix" for that structured syntax when they
   are registered.  By the same token, media types MUST NOT be given
   names incorporating suffixes for structured syntaxes they do not
   actually employ. "+suffix" constructs for as-yet unregistered
   structured syntaxes SHOULD NOT be used, given the possibility of
   conflicts with future suffix definitions.
```

If I'm reading it correctly, it looks like the suffix `+foo` can be used as a generic match for existing type foo. I think the extra check in `jsonBodyParser` seems redundant. I'd be happy with an approach that basically parses out a suffix in `bodyParser`, and use that should the initial match against content-type fail. Thoughts?

**Comment by mattbishop** [comment] 2017-09-03 16:22
Sounds simple enough. You may want to consider adding two unofficial, but used, mime types to the support list: `text/json` and `text/javascript` though the latter might be one too many.

**Closed** 2018-05-27 23:12 UTC
Labels: Critical, Feature, Help Wanted
