### ISSUE TITLE
Bodyparser breaks params on POSTS where the body is an array

### ISSUE THREAD

**Issue by dark12222000** [restify/node-restify#894] opened 2015-09-08 15:51 UTC
This was initially discussed in #718 where a solution is provided but no explanation is given. It seems the bodyparser discards the normal url parameters and instead fills them from the body on POST requests when given an array.

This behavior isn't captured in the [Docs](http://mcavage.me/node-restify/#bundled-plugins) nor does it make any sense for the existing params to be erased and replaced with the body parameters. From a developers perspective, this leads to really weird errors (all of a sudden routes are entirely broken when the body becomes an array).  At the very least, it seems this shouldn't be default behavior and that mapParams should be `false` by default. Even if mapParams is true, it shouldn't remove the other params when it encounters an array.

**Comment by DonutEspresso** [comment] 2015-09-08 17:16
I completely agree - we'll be addressing this behavior in the next major release. We'll be updating both queryParser and bodyParser plugins to conform to the new behavior. 

Marking as dupe of #789.

**Closed by DonutEspresso** 2015-09-08 17:16 UTC

**Comment by DonutEspresso** [comment] 2015-09-08 17:47
FYI, forgot to mention - you can also pass in `overrideParams: false` to keep it from overriding existing parameters.

**Comment by DonutEspresso** [comment] 2015-09-08 17:56
Sorry - just looked through the code - `overrideParams` doesn't appear to be used in the case the value is an array, as you have noted. We'll address all of these surprising behaviors.
