### ISSUE TITLE
string router cann't be set like /foo/

### ISSUE THREAD

**Issue by pillys** [restify/node-restify#723] opened 2014-12-11 03:18 UTC
When set the router via string '/foo/', it can only match '/foo', not '/foo/'.
lib/router.js: line 77, the function compileURL will loss the last '/' when parsing the string to RegExp.

**Comment by DonutEspresso** [comment] 2015-06-13 06:55
Duplicate of #692.

**Closed by DonutEspresso** 2015-06-13 06:55 UTC
