### ISSUE TITLE
Accept Numbers as body in send()

### ISSUE THREAD

**Issue by artushin** [restify/node-restify#1406] opened 2017-07-11 21:31 UTC
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Feature Request
5.0 breaks the ability to send numbers as a body in `send()`. I'd like to add them back.
## Use Case

> Why do you want this?
Backwards compatibility. If an API is already written with Number responses (which are arguably valid JSON), 5.0 breaks the contract.
## Example API

> This should include code snippets and documentation for the proposed feature
`.send(200, 5);`
## Are you willing and able to implement this?

> "Yes" or, if "no", what can current contributors do to help you create a PR?
Yes. I guess booleans probably fall into the same category. I can add those too.

**Comment by retrohacker** [comment] 2017-07-18 00:01
Hey @artushin,

Thanks for pointing this regression out! I believe I introduced it when updating the way we handle optional parameters here: https://github.com/restify/node-restify/blob/5.x/lib/response.js#L273-L277

Is there a reliable way to differentiate between a body that is a `Number` and a status code? I.E. will a status code only be required when using a body of type `Number` as in `resp.send(200, 200)`?

**Comment by retrohacker** [comment] 2017-07-18 00:02
To clarify, we run into the problem where:

Clear: `resp.send(200, '200')`
Clear: `resp.send('200')`
Clear: `resp.send(200, 200)`
Ambiguous: `resp.send(200)`

**Comment by retrohacker** [comment] 2017-07-18 00:03
I'm labeling this as a `bug` since it was a regression and a `feature` since it is technically a "new" thing if we decide to formally support it. Also labeling it as `needs discussion` since, as it stands, this is introducing ambiguity into the API.

**Comment by artushin** [comment] 2017-07-18 01:33
I think you should choose a convention and document it for the last case.
Off the top of my head, a status code makes the most sense there
semantically but I would go with whatever maintains the old API convention
in order to prevent regressions.

**Comment by kokarn** [comment] 2017-08-04 08:49
I think the last case should also be a status code. 
If somebody want's to implement something like that they should probably specify a explicit status code.

**Comment by retrohacker** [comment] 2017-08-11 19:35
@yunong @rajatkumar @DonutEspresso thoughts?

**Comment by DonutEspresso** [comment] 2017-08-16 06:06
Agree with status code, I think it would be more confusing to break that API given the historical/legacy use cases.

**Comment by hekike** [comment] 2018-04-10 18:01
Fixed by: https://github.com/restify/node-restify/pull/1609

**Closed by hekike** 2018-04-10 18:01 UTC
Labels: Bug, Good First Issue, Help Wanted
