### ISSUE TITLE
Missing 'content-type' header for errors generated by Restify

### ISSUE THREAD

**Issue by simonepri** [restify/node-restify#1436] opened 2017-08-06 07:37 UTC
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

# Bug Report
Errors generated internally from Restify does not have a content-type set for the response and fails to choose the right formatter for the response.

## Restify Version

`restify@5.0.1`

## Node.js Version

`node@8.1.4`

## Expected behaviour

Errors generated from Restify should have the `'application/json'` header setted as default.
They should not fall into the custom formatter I've defined.

## Actual behaviour

Currently this is the formatters chain:
https://github.com/restify/node-restify/blob/5.x/lib/formatters/index.js

But as you can see the error falls into the formatter I've defined.
![image](https://user-images.githubusercontent.com/3505087/29001351-933118aa-7a88-11e7-9fa5-8dc5a5f4f0b5.png)

## Repro case

```
const restify = require('restify');

server = restify.createServer({
  formatters: {
      'application/xml; q=0.0': (req, res, body) => {
        console.log('Response \'content-type\':', res.header['content-type']);
        return (body) ? body.toString() : '';
      }
    }
});

server.listen(2300, () => {
  console.log('%s listening at %s', server.name, server.url);
});

server.on('NotFound', (req, res, err, cb) => {
  console.log('NotFound error thrown!')
  cb();
});
```

## Cause

The addition of

> res.setHeader('content-type', 'application/json');

before send the error could solve the problem.

https://github.com/restify/node-restify/blob/5.x/lib/server.js#L215
https://github.com/restify/node-restify/blob/5.x/lib/server.js#L219

## Workaround
```

function setErrContentType (req, res, err, cb)  {
    res.setHeader('Content-Type', 'application/json');
    cb();
}

server.on('NotFound', setErrContentType);
server.on('MethodNotAllowed', setErrContentType);
server.on('VersionNotAllowed', setErrContentType);
server.on('UnsupportedMediaType', setErrContentType);

```
## Are you willing and able to fix this?
"Yes" but I want to know if this is a bug or an expected behaviour.

**Comment by simonepri** [comment] 2017-08-06 08:40
From the Documentation:
![image](https://user-images.githubusercontent.com/3505087/29001750-6cd02eb6-7a93-11e7-9306-ffbbccd6784e.png)

The user expects the error to have the proper header setted.
Am I wrong? @retrohacker

**Comment by DonutEspresso** [comment] 2017-08-06 21:23
Hi @simonepri, what client are you using to issue the request? It could be that restify is unable to negotiate an appropriate content-type to use, in which case it _should_ be falling back on `application/octet-stream` as the default. If I use curl against your repro case, I get back the expected headers:

```sh
$ curl -i localhost:2300
HTTP/1.1 404 Not Found
Server: restify
Content-Type: application/json
Content-Length: 56
Date: Sun, 06 Aug 2017 21:21:09 GMT
Connection: keep-alive

{"code":"ResourceNotFound","message":"/ does not exist"}
```

**Comment by simonepri** [comment] 2017-08-06 21:29
Hello @DonutEspresso, thank for the answer.

I've issued the request to the endpoint from
`Chrome 61.0.3163.31`

**Comment by DonutEspresso** [comment] 2017-08-06 22:21
Ah, this is expected behavior from content-type negotiation. Here is the browser's accept header on the request from the network tab:

```js
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
```

In this case, since your response has not specified a content-type (using `res.header('content-type')`) restify tries to find the content-type most suitable, in order of what the browser has asked for. In this case, the first match is xml. If you remove your xml formatter, then restify doesn't know how to serve an xml content-type, so it falls back on application/json (which is covered under the */*). 

If you want to have an xml formatter defined for other endpoints but send a JSON, you need to explicitly set content-type as in your workaround  example (you could also do it via a middleware if you know which endpoints need application/json). Hope that helps!

**Comment by simonepri** [comment] 2017-08-06 22:40
Thank you for your amazing explanation!! Really!

Errors are not always meant to be sent as JSON? Why do not set that header as default?

**Comment by DonutEspresso** [comment] 2017-08-16 06:16
Based on http content negotiation rules, it would be wrong for restify to force set a content-type if the requesting client prefers another content type. It may be that the client doesn't even support application/json, in which case restify would fall back to text/plain or application/octet-stream. 

As for your example, you'll notice content-type is set after the formatter has been invoked. The browser will get a content-type header of application/xml. I'll close this issue for now, since this is the expected behavior.

**Closed by DonutEspresso** 2017-08-16 06:16 UTC
Labels: Bug, Needs Discussion
