### ISSUE TITLE
restify.CORS - error in documentation I guess

### ISSUE THREAD

**Issue by alekbarszczewski** [restify/node-restify#573] opened 2014-03-28 11:22 UTC
At http://mcavage.me/node-restify/#Bundled-Plugins, CORS it stands:

`server.use(restify.CORS())`

I guess it should be `server.pre(restify.CORS());` at least only with `pre` it work for me.
Also you should mention about `restify.fullResponse()` there.
Just spent one hour trying to handle CORS.

**Comment by jamesjara** [comment] 2015-01-03 06:52
thanks°° +1

**Comment by sydcanem** [comment] 2015-04-21 10:41
Got me scratching for an entire afternoon for this one. I guess there might be something wrong with `restify.CORS()` and `restify.fullResponse` because preflight errors are intermittent. Now I'm using node-cors module as replacement to `restify.CORS()` and it worked without the errors now.

```
var cors = require('cors');

server.use(cors());
server.use(restify.fullResponse());
```

**Comment by yunong** [comment] 2015-04-21 16:14
Can you send a case to reproduce?

On Tuesday, April 21, 2015, James Santos <notifications@github.com> wrote:

> Got me scratching for an entire afternoon for this one. I guess there
> might be something wrong with restify.CORS() and restify.fullResponse
> because preflight errors are intermittent. Now I'm using node-cors module
> as replacement to restify.CORS() and it worked without the errors now.
>
> var cors = require('cors');
>
> server.use(cors());
> server.use(restify.fullResponse());
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mcavage/node-restify/issues/573#issuecomment-94741598>
> .
>


-- 
Via mobile

**Comment by retrohacker** [comment] 2017-06-27 18:53
Thanks everyone for patiently waiting for an update on CORS. The module now lives at https://github.com/TabDigital/restify-cors-middleware/ 

It also has been completely revamped to properly handle CORS requests :tada:! There is a new documentation website coming in the near future, and the current docs are being deprecated. Closing this issues as resolved for now :heart: if I'm missing a nuance and these issues are not resolved, comment and we can re-open to discuss!

**Closed by retrohacker** 2017-06-27 18:53 UTC
Labels: improvement, PR in flight

**Comment by BrunoES** [comment] 2022-06-16 02:23
+ 1 thanks!
