### ISSUE TITLE
Ambigous Route Matching

### ISSUE THREAD

**Issue by robwilkerson** [restify/node-restify#815] opened 2015-05-28 14:29 UTC
This may not be a bug, but I'd like to at least better understand what I'm seeing. I'm looking at 2 routes that are admittedly ambiguous. In the order in which they appear in my `routes/index.js` file:

```
server.get({ path: '/users/authorize', name: 'authorize', version: ['1.0.0', '1.8.0'] }, users.authorize);
server.get({ path: '/users/:id', version: ['1.0.0', '1.8.0'] }, users.get);
```

If I make a request for `GET /users/authorize` that passes _no_ `Accept-Version` value, the `/users/authorize` route gets matched and `users.authorize()` callback is executed which is, of course, what I'm after.

On the other hand, if i pass `Accept-Version: 1.8.0`, the `/users/:id` route gets matched and the `users.get()` callback gets executed.

I have a `server.pre()` function in place that defaults unspecified version values to 1.0.0. I don't know if/how that factors in, but it very well could matter:

```
server.pre(function (req, res, next) {
  if (!req.headers['accept-version']) {  // request headers seem to get normalized to lower case
    req._version = '1.0.0';
  }

  return next();
});
```

I have a "fix" in place to redirect the request if I land in the wrong place, but it's a hack. I'd really like to understand how the route is getting matched so I can implement something more solid.

Thanks.

**Comment by yunong** [comment] 2015-05-29 03:18
@robwilkerson could you gist or send a bare bones server that reproduces this behaviour? I can take a look and see if this is a bug.

**Comment by robwilkerson** [comment] 2015-05-29 18:44
Thanks, @yunong. It'll take a little time for me to do that. In the meantime, am I correct in understanding that Restify _should_ match the first route or could it be completely arbitrary on any given request? I read something indicating that it might based on whatever order the engine returns its `Object.keys()`, but I don't recall the context.

**Comment by orozcojair** [comment] 2016-04-18 18:00
Hi guys, I am currently experiencing this issue as well. I can definitely provide you with my sample server, should I just paste it here or zip it and send it somewhere.

Thank you for the great work @yunong and company

**Comment by orozcojair** [comment] 2016-04-18 18:18
@robwilkerson I know this is from a year ago, but where you able to resolve this in a elegant way? right now my solution is to name my endpoint "/items/find/?id" instead of "/items/:id" and just taking the id from the URL which is the most elegant way...

**Comment by robwilkerson** [comment] 2016-04-18 18:22
@orozcojair I _believe_ I used regex routing. For example, `/items/find/:id(^[\d]+$)` (indicating that the `:id` parameter must contain 1 or more decimals and nothing else. Maybe that helps?

**Comment by orozcojair** [comment] 2016-04-18 18:40
@robwilkerson that is a good point! i could use regex to redirect to the desired route. But hopefully they can get this resolved in a more natural way, but thank you for your comment, im definitely going to implement it to make it less weird for my consumers

**Comment by orozcojair** [comment] 2016-04-18 18:42
Here is a barebones server that shows the issue I am having (minus the newly added suggestion to use regex)
[ambiguos_route.zip](https://github.com/restify/node-restify/files/224489/ambiguos_route.zip)

**Comment by DonutEspresso** [comment] 2016-04-29 00:44
Hi @orozcojair, thank you for the example! That helps a lot. It definitely looks like a bug. If you have ambiguous routes, it appears the first route registered takes precedence. So in this case, as a temporary workaround, you'll probably want to register the static routes first, with any dynamic ones afterward.

Thanks for the bug report, we'll try and get this fixed soon.

**Comment by hairichuhe** [comment] 2016-07-12 03:37
你们个这个问题怎么解决了，有完美的方案吗，我试了，好像正则是最完美最严格的

**Comment by hairichuhe** [comment] 2016-07-12 03:44
i try it, like this likely '/api/user/'+/\d+|\d+\?\./sove this question but it’s ugly

**Comment by hekike** [comment] 2018-04-03 18:28
Restify v7.x has a new router layer, please check this out.

**Closed by hekike** 2018-04-03 18:28 UTC
Labels: Bug, Help Wanted
