### ISSUE TITLE
serveStatic doesn't seem to work as desired

### ISSUE THREAD

**Issue by tnguyen14** [restify/node-restify#1298] opened 2017-03-29 23:40 UTC
I am trying to use the serveStatic method like so:
```js
server.get(/\/docs\/?.*/, restify.serveStatic({
    directory: './doc',
    default: 'index.html'
}));
```
however, when I go to `https://myapp.com/docs/`, I get this error: `{"code":"ResourceNotFound","message":"/docs/"}`
I think this is because if I don't define file in opts, it defaults to `directory` +` req.path()`, which becomes `doc/docs`
this is not the desired behavior, and doesn't seem to be the behavior described in the documentation
> The above `route` and `directory` combination will serve a file located in `./documentation/v1/docs/current/index.html` when you attempt to hit `http://localhost:8080/docs/current/`.

does anyone know what I need to do to get the behavior that I wanted?

I cannot set `file: index.html`, because that will serve that same file for all static request to `docs`, which will basically break the site.

**Comment by retrohacker** [comment] 2017-04-26 23:44
This appears to be a duplicate of #535

If I'm missing something please let me know :heart:

**Closed** 2017-04-26 23:51 UTC
